### ISSUE TITLE
T0.1 - Prepare Mockups

### ISSUE THREAD

**Issue by iremacildi** [iremacildi/SWE574-Group03#19]
- Promoted/Recommended Events and Offers Section
- Admin Dashboard
- Activity Stream
- Follow / Unfollow

**Comment by ugurduz** [comment]
![Page1](https://user-images.githubusercontent.com/65074451/161581003-ffd6f468-ba75-48be-a692-aafeb27bd1bb.png)
![Page2](https://user-images.githubusercontent.com/65074451/161581022-1a8d0721-f952-44a3-9cf3-db05069d659c.png)

**Comment by anilkilickaplan** [comment]
Done
