### ISSUE TITLE
T0.2 - UML Design

### ISSUE THREAD

**Issue by anilkilickaplan** [iremacildi/SWE574-Group03#35]
- Class Diagram 
- Sequence Diagram

**Comment by anilkilickaplan** [comment]
Class Diagram is cloned from Arcan's work on Draw.io. Due to technical problems on google drive sharing, I will try to reinstall and share with the team asap.

![image](https://user-images.githubusercontent.com/70136838/160302627-de48588d-f8e0-40fb-bc41-63a2c041c7f0.png)

**Comment by ugurduz** [comment]
![class v2](https://user-images.githubusercontent.com/65074451/162446199-978815a7-3272-4345-aab9-a42db7bac2e3.png)

**Comment by ugurduz** [comment]
![class v3](https://user-images.githubusercontent.com/65074451/162446686-73cbe21c-f8d2-4f66-b8a6-d5c9c628f6c1.png)

**Comment by ugurduz** [comment]
![usecase v2](https://user-images.githubusercontent.com/65074451/162447047-d7331e7a-8b65-421d-a294-be89c306729e.png)

**Comment by ugurduz** [comment]
![class v4](https://user-images.githubusercontent.com/65074451/162499732-cd4b4ca0-0408-4e92-8d20-0f477c6b65d9.png)

**Comment by iremacildi** [comment]
![SD04 1](https://user-images.githubusercontent.com/6725424/162551076-85818e7b-6667-4dca-a4e0-653dafed7589.png)
![SD04 2](https://user-images.githubusercontent.com/6725424/162551079-4e4be4dd-7484-4a24-ae3d-cd5b5f8b7427.png)
![SD05](https://user-images.githubusercontent.com/6725424/162551084-18f14dc9-37a1-40dd-99ea-28a1cb105eb5.png)
![SD12](https://user-images.githubusercontent.com/6725424/162551086-c40c0b36-d125-4308-ac81-8d06abca6e8a.png)
![SD13](https://user-images.githubusercontent.com/6725424/162551087-2583c7bf-d80f-4369-b46a-5cb1d0b5c535.png)
![SD14](https://user-images.githubusercontent.com/6725424/162551089-a0bbf332-86c7-4e82-9495-ef451e38482c.png)

**Comment by anilkilickaplan** [comment]
Done

**Comment by ugurduz** [comment]
![SWE574_SequenceDiagram-Class Diagram drawio](https://user-images.githubusercontent.com/65074451/162641870-c67f5074-8864-462c-80ed-aeb80cf340a7.png)

**Comment by ugurduz** [comment]
![SWE574_SequenceDiagram-Use case drawio](https://user-images.githubusercontent.com/65074451/162641919-14a52c2f-5ece-4ad0-8d92-cc75754fb6ae.png)

**Comment by anilkilickaplan** [comment]
<img width="663" alt="image" src="https://user-images.githubusercontent.com/70136838/162720689-8092b0e4-3af0-4cb5-8cb7-17489971f137.png">

<img width="643" alt="image" src="https://user-images.githubusercontent.com/70136838/162720751-f7c7a9d9-5dc8-4081-97cd-e263016d4f4e.png">
