### ISSUE TITLE
T9. Continous Integration

### ISSUE THREAD

**Issue by anilkilickaplan** [iremacildi/SWE574-Group03#44]
Let's ship the product! ⛵️

**Comment by iremacildi** [comment]
http://eventify-env.eba-wwy83c8u.us-east-1.elasticbeanstalk.com/

**Comment by iremacildi** [comment]
**commands for ec2 ssh connection;**

- eb init --interactive
- eb ssh
- sudo su -
- ls /var/app
- cd /var/app
- sudo find / -name main.css

**Comment by iremacildi** [comment]
**elastic beanstalk configuration/software;**

WSGI Path: web.wsgi

proxy settings for static files;
/static :arrow_right: static
/static/css :arrow_right: /web/static/css
/static/star-ratings :arrow_right: ../venv/staging-LQM1lest/lib/python3.8/site-packages/star_ratings/static/star-ratings
