### ISSUE TITLE
T4.1 - Notify Attendees for Event/Service Update

### ISSUE THREAD

**Issue by iremacildi** [iremacildi/SWE574-Group03#7]
When anything is changed by the organizer regarding the event or service, approved attendees will be notified on the web application.

Developers Note:
- Notification will be triggered by the update.

**Comment by anilkilickaplan** [comment]
Developers Note:

- Notification number will not be visible after the user clicks on the notification button.
- Notifications will be order descending by the notification date.
- Max amount of Notification items in Notification button will be 10.
- More than 10 will be displayed on notification page.

**Comment by anilkilickaplan** [comment]
- [ ] Task allocation will be discussed in the meeting, 4th of April.

**Comment by ugurduz** [comment]
![Page2](https://user-images.githubusercontent.com/65074451/162640615-4d78060a-8114-4e9c-9ecb-ec70a42b0c67.png)

**Comment by iremacildi** [comment]
run `python manage.py migrate notifications` and `pip install -r requirements.txt`
